(defalias 'af 'auto-fill-mode)
(defalias 'b 'ibuffer)
(defalias 'beamer 'presentation-mode)
(defalias 'dir 'dired)
(defalias 'es 'eshell)
(defalias 'fl 'font-lock-mode)
(defalias 'gws 'global-whitespace-mode)
(defalias 'mb 'menu-bar-mode)
(defalias 'res 'reset-themes)
(defalias 'sh 'shell-script-mode)
(defalias 'term 'run-term)
(defalias 'ws 'whitespace-mode)
(defalias 'yas 'yas-force-update)
(defalias 'yas 'yas-force-update)
(defalias 'yas 'yas-force-update)

(defalias 'rxvt 'run-rxvt)
(defalias 'rx 'run-rxvt)
(defalias 'xt 'run-xterm)
(defalias 'xterm 'run-xterm)
(defalias 'fterm 'run-fterm)
(defalias 'bterm 'beamer-term)
(defalias 'bt 'beamer-term)

(defalias 'default-theme 'custom-default-theme)
(defalias 'deft 'custom-default-theme)
(defalias 'cycle-theme 'custom-cycle-theme)
(defalias 'ct 'custom-cycle-theme)
(defalias 'dt 'disable-all-themes)
(defalias 'lt 'load-theme)

(defalias 'ln 'display-line-numbers-mode)

(defalias 'knuth 'knuth-font)
(defalias 'meslo 'menlo-font)
(defalias 'menlo 'menlo-font)
(defalias 'ttf    'menlo-font)
(defalias 'go     'go-font)
(defalias 'dejavu 'dejavu-font)

(defalias 'cf 'conf-mode)
