;;; global aliases of default functions
;; modesp

(defalias 'af            'auto-fill-mode)
(defalias 'cf            'conf-mode)
(defalias 'fl            'font-lock-mode)
(defalias 'gfl           'globalfont-lock-mode)
(defalias 'fontify       'font-lock-fontify-buffer)
(defalias 'hs            'haskell-mode)
(defalias 'gws           'global-whitespace-mode)
(defalias 'wsg           'global-whitespace-mode)
(defalias 'ws            'whitespace-mode)
(defalias 'mb            'menu-bar-mode)
(defalias 'sh            'shell-script-mode)
(defalias 'zsh           'shell-script-mode)
(defalias 'li            'lisp-interaction-mode)
(defalias 'el            'emacs-lisp-mode)
(defalias 'org           'org-mode)
(defalias 'txt           'text-mode)
(defalias 'ppt           'puppet-mode)
(defalias 'fm            'fundamental-mode)
(defalias 'oc            'occur)
(defalias 'win           'shell)
(defalias 'term          'ansi-term)
(defalias 'tex           'plain-tex-mode)
(defalias 'latex         'latex-mode)
;;
(defalias 'xt            'xterm-mouse-mode)
(defalias 'ap            'apropos)
(defalias 'qc            'quick-calc)
(defalias 'dir           'dired-jump)
(defalias 'linum         'display-line-numbers-mode)
(defalias 'tr            'toggle-truncate-lines)
(defalias 'sf            'set-fill-column)
(defalias 'fci           'display-fill-column-indicator-mode)
;;
(defalias 'win-undo      'winner-undo)
(defalias 'win-redo      'winner-redo)
(defalias 'wundo         'winner-undo)
(defalias 'wredo         'winner-redo)
(defalias 'qr            'query-replace)
(defalias 'qrr           'query-replace-regexp)
(defalias 'b             'balance-windows)
;;
(defalias 'conf          'conf-mode)
(defalias 'ro            'read-only-mode)
(defalias 'er            'read-only-mode)
(defalias 'rw            'read-only-mode)
