;; modes
(defalias 'af            'auto-fill-mode)
(defalias 'beamer        'presentation-mode)
(defalias 'cf            'conf-mode)
(defalias 'fl            'font-lock-mode)
(defalias 'gws           'global-whitespace-mode)
(defalias 'ws            'whitespace-mode)
(defalias 'ln            'display-line-numbers-mode)
(defalias 'mb            'menu-bar-mode)
(defalias 'sh            'shell-script-mode)
(defalias 'sw            'subword-mode)
(defalias 'pp            'puppet-mode)
(defalias 'txt           'text-mode)
;; term
(defalias 'bt            'beamer-term)
(defalias 'bterm         'beamer-term)
(defalias 'rx            'run-term)
(defalias 'rxvt          'run-term)
;;(defalias 'term          'run-rxvt)
(defalias 'xt            'run-xterm)
(defalias 'xterm         'run-xterm)
(defalias 'term          'ansi-term)
;; themes
(defalias 'ct            'custom-cycle-theme)
(defalias 'cycle-theme   'custom-cycle-theme)
(defalias 'default-theme 'custom-default-theme)
(defalias 'deft          'custom-default-theme)
(defalias 'dft           'custom-default-theme)
(defalias 'dt            'disable-all-themes)
(defalias 'lt            'load-theme)
(defalias 'res           'reset-themes)
;; fonts
(defalias 'menlo         'menlo-font)
(defalias 'ttf           'menlo-font)
;; misc
(defalias 'b             'ibuffer)
(defalias 'dir           'dired)
(defalias 'es            'eshell)
(defalias 'linum         'display-line-numbers-mode)
(defalias 'yas           'yas-force-update)
(defalias 'tr            'toggle-truncate-lines)
(defalias 'trunc         'toggle-truncate-lines)
(defalias 'sf            'set-fill-column)
