(custom-set-variables
 '(blink-cursor-mode nil)
 '(column-number-mode t)
 '(cua-mode nil)
 '(display-battery-mode nil)
 '(display-time-mode nil)
 '(inhibit-startup-screen t)
 '(tool-bar-mode nil)
 '(scroll-bar-mode (quote nil))
 '(show-paren-mode t)
 '(size-indication-mode t)
 '(menu-bar-mode nil)
 '(tooltip-mode nil))
(custom-set-faces
 '(dired-directory ((t (:foreground "brightblue"))))
 '(dired-symlink ((t (:foreground "magenta"))))
 '(font-lock-builtin-face ((t (:foreground "magenta"))))
 '(font-lock-comment-face ((t (:foreground "red"))))
 '(font-lock-constant-face ((t (:foreground "green"))))
 '(font-lock-function-name-face ((t (:foreground "magenta"))))
 '(font-lock-keyword-face ((t (:foreground "cyan"))))
 '(font-lock-string-face ((t (:foreground "green"))))
 '(font-lock-type-face ((t (:foreground "green"))))
 '(font-lock-variable-name-face ((t (:foreground "yellow"))))
 '(mode-line ((t (:inverse-video t))))
 '(mode-line-inactive ((t (:inverse-video nil))))
 '(minibuffer-prompt ((t (:inherit foreground))))
 '(region ((t (:foreground "white" :background "blue" :extend t))))
 '(cua-rectangle ((t (:foreground "white" :background "maroon" :extend t)))))

(setq vc-follow-symlinks t)

(ido-mode t)
(setq ido-enable-flex-matching t)
(setq ido-auto-merge-work-directories-length -1)
(setq ido-default-buffer-method 'selected-window)
(setq ido-default-file-method 'selected-window)

(add-to-list 'load-path "~/.emacs.d/elisp")
(load-library "custom-aliases")
(load-library "custom-editing")
(load-library "custom-keys")
(load-library "custom-dired-mode")

;; manage backups/autosaves
(load-library "backup-autosave")
